INSERT INTO CUSER (USER_ID, NAME, PASSWORD, NICKNAME, ACTIVATED) VALUES (1, 'admin', '21joaidhDuioIJDIJAIadwah2oh4UHAUA2', 'ADMIN', 1);

INSERT INTO AUTHORITY(AUTHORITY_ID, NAME) VALUES (1, 'ROLE_USER');
INSERT INTO AUTHORITY(AUTHORITY_ID, NAME) VALUES (2, 'ROLE_ADMIN');

INSERT INTO USER_AUTHORITY(user_authority_id, user_id, authority_id) VALUES (1, 1, 1);
INSERT INTO USER_AUTHORITY(user_authority_id, user_id, authority_id) VALUES (2, 1, 2);