INSERT INTO CUSER (USER_ID, NAME, PASSWORD, NICKNAME, ACTIVATED) VALUES (1, 'admin', '$2a$12$XEhnFla7rRrLnd/GNTJLyu9mcYHie5EcY/uFzUhklBAxfQUP7ThOG', 'ADMIN', 1);

INSERT INTO AUTHORITY(AUTHORITY_NAME) VALUES ('ROLE_USER');
INSERT INTO AUTHORITY(AUTHORITY_NAME) VALUES ('ROLE_ADMIN');

INSERT INTO USER_AUTHORITY(user_authority_id, user_id, authority_name) VALUES (1, 1, 'ROLE_USER');
INSERT INTO USER_AUTHORITY(user_authority_id, user_id, authority_name) VALUES (2, 1, 'ROLE_ADMIN');